_target_: datasets.FreiPoseDataset
folder_path: 'C:\\Users\\filip\\Downloads\\FreiPoseMini'
set_type: 'training'
image_extension: '.jpg'
transform:
  _target_: transforms.DatasetTransform
  value: FREI_POSE