_target_: datasets.FreiPoseDataset
folder_path: 'C:\\datasets\\FreiPose'
set_type: 'training'
image_extension: '.jpg'
resize: 192
original_size: 224
transform:
  _target_: transforms.DatasetTransform
  value: FREI_POSE