defaults:
  - model: unet
  - dataset: frei_pose
  - optimizer: sgd_pose
  - trainer: frei_trainer
  - _self_

debug: true

# Loss calculation params
loss:
  _target_: torch.nn.MSELoss
input_key: 'image'
output_key: 'heatmaps'

# Dataset params
batch_size: 5
train_ratio: 0.9

# Checkpoint callback
checkpoint_callback:
  _target_:  pytorch_lightning.callbacks.ModelCheckpoint
  monitor: 'val_loss'
  dirpath: 'model/'
  filename: 'model-{epoch:02d}-{val_loss:.2f}'
  save_top_k: 3
  mode: 'min'

# W&B logger
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: 'pose-estimation'
  job_type: 'train'
