defaults:
  - model: pose_resnet_frei_baseline
  - dataset: frei_pose
  - optimizer: adam_pose
  - trainer: frei_trainer
  - _self_

debug: true

# Loss calculation params
loss:
  _target_: losses.iou_loss.IoULoss
input_key: 'image'
output_key: 'heatmaps'
lr: 0.001
pck_ratio: 0.2

# Dataset params
batch_size: 48
train_ratio: 0.95

# Checkpoint callback
checkpoint_callback:
  _target_:  pytorch_lightning.callbacks.ModelCheckpoint
  monitor: 'val_loss'
  dirpath: ''
  filename: 'model-{epoch:02d}-{val_loss:.2f}'
  save_top_k: 3
  mode: 'min'

# W&B logger
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: 'Frei Pose Estimation'
  name: ''
  job_type: 'train'


hydra:
  sweeper:
    params:
      +model: pose_hrnet_onehand_baseline,posemobilenet_onehand_baseline
