defaults:
  - model: vgg_style_transfer
  - dataset@train_dataset: rendered
  - dataset@target_dataset: frei
  - optimizer: adam_pose
  - trainer: frei_trainer
  - _self_

debug: true

pretrain: "C:\\models\\checkpoints\\decoder_s2h_0_1.pth.tar"
lr: 0.001

# Dataset params
batch_size: 12
train_ratio: 0.96

# Style transfer params
content_weight: 1.0
style_weight: 0.1

# Checkpoint callback
checkpoint_callback:
  _target_:  pytorch_lightning.callbacks.ModelCheckpoint
  monitor: 'val_total_loss'
  dirpath: ''
  filename: 'model-{epoch:02d}-{val_total_loss:.2f}'
  save_top_k: 3
  mode: 'min'

# W&B logger
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: 'Style Transfer'
  name: ''
  job_type: 'train'
