defaults:
  - model: baseline_mmpose
  - dataset: frei_pose
  - optimizer: adam_pose
  - trainer: frei_trainer
  - _self_

debug: true

# Loss calculation params
loss:
  _target_: losses.iou_loss.IoULoss
input_key: 'image'
output_key: 'heatmaps'
lr: 0.0069
pck_ratio: 0.05

# Dataset params
batch_size: 48
train_ratio: 0.95

# Checkpoint callback
checkpoint_callback:
  _target_:  pytorch_lightning.callbacks.ModelCheckpoint
  monitor: 'val_loss'
  dirpath: 'model/'
  filename: 'model-{epoch:02d}-{val_loss:.2f}'
  save_top_k: 3
  mode: 'min'

# W&B logger
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: 'frei-pose-estimation-mmpose-testing'
  name: '20231105_baseline_mmpose'
  job_type: 'train'
